{"frames":[{"func":"use_github()","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"git_default_branch()","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"usethis_abort(c(\"Default branch mismatch between local repo and remote.\", \n    \"The default branch of the {.val {db_source$name}} remote is\\n     {.val {db_source$default_branch}}.\", \n    \"But the default branch of the local repo appears to be\\n     {.val {db_local_with_source}}.\", \n    \"Call {.code git_default_branch_rediscover()} to resolve this.\"),  ...","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"cli::cli_abort(message, class = c(class, \"usethis_error\"), .envir = .envir, \n    ...)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"rlang::abort(message, ..., call = call, use_cli_format = TRUE, \n    .frame = .frame)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"signal_abort(cnd, .file)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"stop(fallback)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error in git_default_branch() : \u001B[38;5;232m\nThe default branch of the \u001B[34m\"origin\"\u001B[38;5;232m remote is \u001B[34m\"main\"\u001B[38;5;232m.\nBut the default branch of the local repo appears to be \u001B[34m\"master\"\u001B[38;5;232m.\nCall `git_default_branch_rediscover()` to resolve this.\u001B[39m\n"}